languages: [fr_FR,en_US,es_ES,de_DE]
permalink: /:path/:basename
kramdown:
  input: GFM
  parse_block_html: true
site_name:
  fr_FR: Documentation Jeedom
  en_US: Jeedom Documentation
  es_ES: Documentación de Jeedom
  de_DE: Jeedom-Dokumentation
